### ISSUE TITLE
[Bug] l'esercizio "it/javascript/templateLiterals/22.md" ha un problema

### ISSUE THREAD

**Issue by Nicoave97** [nank1ro/codigo-questions#105]
Salve, sulla vostra app codigo nella sezione stringhe template del linguaggio JS, 
![Screenshot_2022-07-27-12-19-46-361_com nank1ro learntocode huawei](https://user-images.githubusercontent.com/102794516/181224082-bd2e985b-2c84-4f55-80e7-3f746220188e.jpg)
In questa domanda mancano le parentesi tonde la mi da tutte le risposte errate e quindi non mi fa completare la quest

**Comment by nank1ro** [comment]
Grazie per la segnalazione, 

La risposta corretta è:
 - Nulla è sbagliato nel codice
