### ISSUE TITLE
[Bug] exercise "en/python/variables/4.md" has an issue

### ISSUE THREAD

**Issue by lolrida** [nank1ro/codigo-questions#106]
When i wrong an a exercise and I’ll rewrite the right answer, i press again on the retry’s button but it gives me the possibility to go to the next page.

**Comment by nank1ro** [comment]
Hello, I found a bug on the app.
I'm releasing the version 2.0.16 that fixes this issue.

Thank you for your report.

@all-contributors please add @lolrida for bug

**Comment by nank1ro** [comment]
Please update the app to the latest version, you should see the issue resolved.

If you encounter any other bug, please consider opening a new issue.
