### ISSUE TITLE
[Bug] l'esercizio "it/python/arithmeticOperators/19.md" ha un problema

### ISSUE THREAD

**Issue by Kaaaaaaboom** [nank1ro/codigo-questions#109]
Stampa il prodotto tra pezzi e prezzo
Pezzi=5
Prezzo=6.5
Print(pezzi*prezzo)

Sbagliato perché  ?

**Comment by nank1ro** [comment]
Ciao, puoi riprovare ad eseguire l'esercizio? Ieri è stata effettuata la migrazione ad un nuovo server, e ci sono stati dei problemi di compilazione.

**Comment by Kaaaaaaboom** [comment]
Ho risolto usando il Tab invece che lo spazio che usavo di solito. Grazie mille
