### ISSUE TITLE
[Bug] l'esercizio "it/kotlin/variables/5.md" ha un problema

### ISSUE THREAD

**Issue by FalconStike** [nank1ro/codigo-questions#110]
Scritto con sintassi giusta, tutto corretto ma segna errore, risolvete per favore, non posso andare avanti :(     
![B51AB11F-8493-4BC4-9E98-B743F91CF3F6](https://user-images.githubusercontent.com/112663162/188012765-b0fd7f64-d296-4962-843c-b5b36b1ad2da.png)     
   
![6966CF91-1E29-4FA7-B7DF-1CB655ECD9E6](https://user-images.githubusercontent.com/112663162/188012820-2d7b5cce-f238-4dfe-87b3-7837e97fa167.png)

**Comment by nank1ro** [comment]
Grazie per la segnalazione, ho già deployato il fix sul server, appena riprovi ti dovrebbe funzionare.

**Comment by nank1ro** [comment]
@all-contributors please add @FalconStike for bug
