### ISSUE TITLE
[Bug] l'esercizio "it/kotlin/booleans/4.md" ha un problema

### ISSUE THREAD

**Issue by FalconStike** [nank1ro/codigo-questions#112]
Hello there.
Ho trovato un altro bug.
La risposta è esatta ma il button per andare avanti non si attiva. Potreste risolverlo?
Ormai sono una calamita per i bug :)

Quì sotto allego i due screenshots:
![B549E31D-DC76-4917-B0D3-433E4AB3B2CE](https://user-images.githubusercontent.com/112663162/188118061-72947994-8a24-4e92-a186-f4afb2ee8c0f.png)
![DE3C20E3-D090-4248-AEDA-1A6BC240FC76](https://user-images.githubusercontent.com/112663162/188118064-076778d0-2f2e-437e-8cba-7202d272ba40.png)

**Comment by nank1ro** [comment]
Strano questo non lo replico, se riprovi il tasto play continua a non attivarsi?
