### ISSUE TITLE
[Bug] l'esercizio "it/python/whileLoops/5.md" ha un problema

### ISSUE THREAD

**Issue by JacopoNard** [nank1ro/codigo-questions#125]
non fa disporre correttamente gli oggetti dell’esercizio.
di preciso inserisce una parentesi nella riga sottostante rispetto a quella corretta

**Comment by nank1ro** [comment]
non riscontro problemi con l'eserzio.
ecco la soluzione:
```py
contatore = 1
while contatore < 5:
    contatore += 1
    print(contatore)
```
