### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CarloDalCin** [nank1ro/codigo-questions#126]
Nessuna delle opzioni è corretta!

**Comment by nank1ro** [comment]
In merito a quale esercizio ti riferisci?

**Comment by nank1ro** [comment]
chiudo per inattività

**Comment by CarloDalCin** [comment]
Al esercizio sui commenti multi riga di dart

Il lun 19 dic 2022, 11:56 Alexandru Mariuti ***@***.***> ha
scritto:

**Comment by nank1ro** [comment]
Dovrebbe già essere stato risolto, apri l'app, vai nella pagina del profilo e cancella la cache, poi riprova a completare l'esercizio

**Comment by CarloDalCin** [comment]
Perfetto funziona grazie

Il mar 10 gen 2023, 17:34 Alexandru Mariuti ***@***.***> ha
scritto:
