### ISSUE TITLE
[Bug] l'esercizio "it/python/formattedStrings/16.md" ha un problema

### ISSUE THREAD

**Issue by Smileyor** [nank1ro/codigo-questions#130]
<!--
Descrivi il tuo problema nei dettagli, se puoi aggiungi anche uno screeshot.
Scrivi dopo questo commento
ho completato correttamente l’esercizio ma mi dice lo stesso che è errato

**Comment by nank1ro** [comment]
l'esercizio funziona correttamente, ecco la soluzione:
```py
print(f"La larghezza e' di {50} metri e l'altezza e' di {10} metri")
```

**Comment by Smileyor** [comment]
Grazie
