### ISSUE TITLE
[Bug] exercise "en/c/variables/1.md" has an issue

### ISSUE THREAD

**Issue by valevolta0501** [nank1ro/codigo-questions#136]
My answer and the solution are the same but the app says that’s wrong and I can’t go forward 
![IMG_8622](https://github.com/nank1ro/codigo-questions/assets/139982948/160b76d6-c80d-47d3-8b93-d931f0acae66)

**Comment by nank1ro** [comment]
Can you update the app to the latest version and try again?
I'm not experiencing any error with the given exercise.

**Comment by valevolta0501** [comment]
I did update but it gives me the same error
