### ISSUE TITLE
[Bug] exercise "en/c/variables/1.md" has an issue

### ISSUE THREAD

**Issue by valevolta0501** [nank1ro/codigo-questions#139]
I wrote you twice already. The first exercise on variables says my answer is wrong but it’s right because I paid and I can see the solution and it’s the same as my answer. I can’t go forward now and I’m stuck on this and it’s the same problem on many other questions in other chapters. Please fix this!!!
![IMG_8755](https://github.com/nank1ro/codigo-questions/assets/139982948/92a1c9f3-826a-4fea-86bd-09ccc13856c8)

**Comment by nank1ro** [comment]
@all-contributors please add @valevolta0501 for bug

**Comment by nank1ro** [comment]
I found the problem, thank you very much for the report! 😊
Before testing again, please go to the __Profile__ page and tap on the __Delete cache__ button
