### ISSUE TITLE
[Bug] l'esercizio "it/python/arithmeticOperators/19.md" ha un problema

### ISSUE THREAD

**Issue by digloriacal** [nank1ro/codigo-questions#142]
Ho fatto l'esercizio correttamente ma mi dice che è sbagliato.
Ho confrontato l'esercizio con la vostra soluzione.

pezzi = 5
prezzo = 6.5 
Print(pezzi * prezzo)

Soluzione:
pezzi = 5 
prezzo = 6.5 
print(pezzi * prezzo)

**Comment by nank1ro** [comment]
puoi provare `print` invece di `Print`?

**Comment by digloriacal** [comment]
Grazie, l'errore era il mio. 

--
Inviato da Libero Mail
