### ISSUE TITLE
[Bug] exercise "en/javascript/arrays/7.md" has an issue

### ISSUE THREAD

**Issue by KaiLega** [nank1ro/codigo-questions#155]
![IMG_9974](https://github.com/user-attachments/assets/eec49d5a-866b-41de-9851-6bd8447844d0)

The answer “animals” appears just once. Actually there were two of them at the beginning, but after selecting one of them and removing it, that disappeared.

The answers, if swapped or deselected, they should go back to their place

**Comment by nank1ro** [comment]
fixed in the v2.6.3 I just released
