### ISSUE TITLE
[Bug] exercise "en/dart/variables/9.md" has an issue

### ISSUE THREAD

**Issue by Snowy-T** [nank1ro/codigo-questions#156]
# Typos 

It’s the exercise before this One that has a typo + there was an other Typo but I don’t remember but it was in this section of the course

**Comment by nank1ro** [comment]
closed by https://github.com/nank1ro/codigo-questions/pull/157

**Comment by nank1ro** [comment]
@all-contributors please add @Snowy-T for bug
