### ISSUE TITLE
[Bug] exercise "en/python/dictionaries/3.md" has an issue 

### ISSUE THREAD

**Issue by OdinV** [nank1ro/codigo-questions#19]
Describe your issue in details
I put in the correct answer, i tried it myself on a program: user["profession"]="developer" is correct but comes up as wrong

**Comment by nank1ro** [comment]
Thank you for your report.

I’ll look into it as soon as possible and I’ll let you know here.

**Comment by nank1ro** [comment]
@all-contributors please add @OdinV for bug

**Comment by nank1ro** [comment]
I solved the problem.
On Monday I will update the app to version 2.0.4 and the problem should no longer occur.
For now, I did a little workaround on question 3 to get it working right away.
