### ISSUE TITLE
[Bug] exercise "en/javascript/templateLiterals/4.md" has an issue 

### ISSUE THREAD

**Issue by Vinzelot** [nank1ro/codigo-questions#21]
If i type the correct answer it loads but i cant continue

**Comment by nank1ro** [comment]
Hello, thank you for your report.
I'm not experiencing any error with that exercise.

Are you sure that you typed:
```js
console.log(`${5} friends`);
```
with the backtick <b>`</b> included?

**Comment by nank1ro** [comment]
closing because this is not a real issue.
