### ISSUE TITLE
[Bug] exercise "en/c/formattedStrings/4.md" has an issue 

### ISSUE THREAD

**Issue by adriawh** [nank1ro/codigo-questions#23]
The app gets stuck checking the code

**Comment by nank1ro** [comment]
Hello,

thank you for your report.
I have reproduced the bug that you mentioned. The validation of the exercise fails and remains loading indefinitely.
I'm going to fix it as soon as possible and tomorrow I will release the version 2.0.4 that will fix this bug.

**Comment by nank1ro** [comment]
@all-contributors please add @adriawh for bug

**Comment by nank1ro** [comment]
closing because the version 2.0.4 that fixes this problem is live in both the Play Store and the App Store.
If you encounter this bug again, consider opening a new issue.
