### ISSUE TITLE
[Bug] exercise "it/python/arithmeticOperators/12.md" has an issue 

### ISSUE THREAD

**Issue by brunicorno** [nank1ro/codigo-questions#24]
![F19280BA-4722-4FDB-939E-C895EFD57080](https://user-images.githubusercontent.com/28707292/142744022-3069a412-a7db-445e-a781-05698dc454f4.jpeg)

what have I not understood here? 
number 22 seems to have a space, maybe? 🤥

**Comment by nank1ro** [comment]
Hello, thank you for your report.
It seems like this is the same problem reported in this bug [here](https://github.com/nank1ro/codigo-questions/issues/19).
I've patched all the exercises in the pull request that I linked so you can continue completing the exercises without waiting for the real fix to be released in the version 2.0.4.

The questions have been updated, I've tested the exercise and now it succeeds.

@all-contributors please add @brunicorno for bug

**Comment by nank1ro** [comment]
closing because the version 2.0.4 that fixes this problem is live in both the Play Store and the App Store.
If you encounter this bug again, consider opening a new issue.

**Comment by brunicorno** [comment]
Hello!

thanks, it all worked out fine.
