### ISSUE TITLE
[Bug] exercise "en/c/booleans/12.md" has an issue 

### ISSUE THREAD

**Issue by ghost** [nank1ro/codigo-questions#34]
Hi again. I think my answer is correct, but it says it’s wrong.

![AFEA86BB-73D0-46A4-B7EA-6F50ED9CAAF2](https://user-images.githubusercontent.com/94829947/142851022-8bc9a433-9d7c-42b2-9152-379c04dbc07e.jpeg)

**Comment by nank1ro** [comment]
Hi,
many thanks for the help.
I'm sorry that you encountered another problem.
I have made a PR that fixes the issue, this does not require a new version of the app, so you should be able to complete the exercise without any issues.

**Comment by nank1ro** [comment]
closing because this is fixed.
