### ISSUE TITLE
[Bug] exercise "it/c/arithmeticOperators/20.md" has an issue 

### ISSUE THREAD

**Issue by simolado** [nank1ro/codigo-questions#40]
Can someone tell me where is the error in this code?
![991D0573-62EA-4601-A8F6-F17CAFCC8AD0](https://user-images.githubusercontent.com/91845095/143603667-8309c5ba-0805-4e1c-903b-69776c7e9ddf.png)
Sorry for the language i don’t know how to translate it

**Comment by nank1ro** [comment]
Ciao,
puoi anche scrivere in italiano se preferisci, non vedo alcun errore nel codice che hai scritto.
Sto verificando perché potrebbe essere un altro bug nell'app

**Comment by nank1ro** [comment]
È un problema abbastanza grande.
In parole semplici la validazione degli esercizi non gestisce bene tutti i casi possibili.
Quindi devo uniformare la validazione ed apportare la modifica anche a tutte le domande.
Cercherò di farti avere un fix il prima possibile, ma richiede comunque un nuovo rilascio.
Se tutto va bene questa domenica rilascio la nuova versione, quindi lunedì dovrebbe essere live.

Mi dispiace per i problemi che hai riscontrato

**Comment by simolado** [comment]
Ok va bene, c'è una risposta giusta in alternativa alla mia?

Il Ven 26 Nov 2021, 18:09 Alexandru Mariuti ***@***.***> ha
scritto:

**Comment by nank1ro** [comment]
ho fatto un hotfix sulla domanda, se provi ora dovrebbe funzionare

**Comment by nank1ro** [comment]
Ciao, ho appena mergiato una PR che risolve questo problema in molte domande.
Perché funzioni, assicurati di usare l'ultima versione dell'applicazione (2.0.6) che ho rilasciato oggi.
