### ISSUE TITLE
[Bug] exercise "en/swift/variables/1.md" has an issue 

### ISSUE THREAD

**Issue by cipoleon** [nank1ro/codigo-questions#44]
I tried many things but does not work. What is wrong with this?
![36011DF8-B16E-45BB-85E8-4F234CF7A434](https://user-images.githubusercontent.com/60713159/144142568-76e78447-76cf-46d8-ba7d-e42912724482.png)

**Comment by nank1ro** [comment]
Hi, your code is correct.
There is an issue in the validation of some exercises and I'm working on to fix it as soon as possible.
I'll let you know here when I have news.

related to this PR https://github.com/nank1ro/codigo-questions/pull/42

**Comment by nank1ro** [comment]
@all-contributors please add @cipoleon for bug

**Comment by nank1ro** [comment]
Hi again, I just merged a PR that fixes this problem in many questions.
To have the fix, be sure the use the latest version of the app (2.0.6) that I just released today.
If you encounter again a problem, consider opening a new issue.
