### ISSUE TITLE
[Bug] exercise "it/python/variables/4.md" has an issue 

### ISSUE THREAD

**Issue by DemolitionDark98** [nank1ro/codigo-questions#45]
Help me

**Comment by nank1ro** [comment]
Ciao, qual è il problema?

**Comment by DemolitionDark98** [comment]
Ciao grazie per la risposta,ho risolto il problema da solo

Il giorno mer 1 dic 2021 alle 15:12 Alexandru Mariuti <
***@***.***> ha scritto:
