### ISSUE TITLE
[Bug] exercise "it/python/variables/4.md" has an issue 

### ISSUE THREAD

**Issue by romocetra** [nank1ro/codigo-questions#46]
Describe your issue in details
I write in italian version:
x = “aggiornato”
I write in english version:
x = “updated”

Why is it not correct?

**Comment by nank1ro** [comment]
Ciao,

la punteggiatura smart non è supportata dai linguaggi di programmazione, devi usare `"`  o `'` (in base al linguaggio).
Nella barra che appare sopra alla tastiera trovi entrambi i caratteri che ti ho elencato, altrimenti se preferisci andando nelle __Impostazioni__ del device iOS -> __Generali__ -> __Tastiera__ -> Disabilita la __punteggiatura smart__

**Comment by romocetra** [comment]
Grazie mille!
Ora funziona perfettamente.
