### ISSUE TITLE
[Bug] exercise "en/python/output/2.md" has an issue

### ISSUE THREAD

**Issue by popskully** [nank1ro/codigo-questions#57]
Unable to submit the answer to a python question. The submit button is disabled even though the answer is correct. The app is registering a space after the last input. 
![80C370CF-E412-495A-9B9C-BE4EDB0A3C76](https://user-images.githubusercontent.com/56766619/145886085-d0ad2f5c-c838-4c09-a3c4-5f04704bba28.png)

**Comment by nank1ro** [comment]
Hi, you are missing the open parenthesis
