### ISSUE TITLE
[Bug] l'esercizio "it/python/formattedStrings/16.md" ha un problema

### ISSUE THREAD

**Issue by MatSim93** [nank1ro/codigo-questions#63]
C’è uno “slot” in più che non permette il corretto inserimento delle risposte

**Comment by nank1ro** [comment]
Ciao,
non vedo errori nella domanda.
Ti lascio la soluzione dell'esercizio per confrontarla:
```
print(f"La larghezza e' di {50} metri e l'altezza e' di {10} metri")
```

**Comment by MatSim93** [comment]
Risolto! Grazie mille per l'aiuto!
