### ISSUE TITLE
[Bug] l'esercizio "it/javascript/templateLiterals/4.md" ha un problema

### ISSUE THREAD

**Issue by ludovica-tonelli** [nank1ro/codigo-questions#73]
L'esercizio da esito errato anche se svolto correttamente

**Comment by nank1ro** [comment]
Ciao,

ho appena verificato l'esercizio ed è funzionante.
Ecco la soluzione:
```js
console.log(`${5} amici`);
```

Ti sei ricordat* del simbolo ``    ` ``?
Lo trovi nella view che esce sopra alla tastiera.

**Comment by nank1ro** [comment]
chiudo in quanto non ho ricevuto risposta, se riscontri nuovamente il problema apri una nuova issue
