### ISSUE TITLE
[Bug] l'esercizio "it/javascript/whileLoops/6.md" ha un problema

### ISSUE THREAD

**Issue by crishrpz** [nank1ro/codigo-questions#84]
Ciao ragazzi complimenti per l App ! Sto riscontrando dei problemi nel corso Javascript… nelle lezioni ‘while loops” i testi sono quelli di SWIFT  . Potete controllare?
Grazie ancora 

Cris

**Comment by nank1ro** [comment]
Ciao,
grazie per i complimenti!
Abbiamo già individuato il problema.
Entro domani dovrebbe essere online la versione 2.0.10 che risolve questo bug.

**Comment by crishrpz** [comment]
Ok grazie mille per la risposta.
Attendiamo update!

Saluti

Il giorno dom 3 apr 2022 alle 20:44 Alexandru Mariuti <
***@***.***> ha scritto:

**Comment by nank1ro** [comment]
L'aggiornamento con il fix è online. Il problema si è risolto?

**Comment by crishrpz** [comment]
Ho l’aggiornamento 2.0.10 ma il bug c’è ancora..

Sezione javascript/ while loops.




Grazie


Il giorno mar 5 apr 2022 alle 08:56 Alexandru Mariuti <
***@***.***> ha scritto:

**Comment by nank1ro** [comment]
Se intendi il fatto che la teoria e gli esercizi sono simili, è una cosa voluta.
Però il linguaggio usato dovrebbe essere diverso.

In realtà ho in mente di fornire teorie diverse sugli stessi argomenti nei vari linguaggi di programmazione, ma al momento non ho abbastanza tempo per rifare le domande.

**Comment by crishrpz** [comment]
Si è il linguaggio che dovrebbe essere Javascript e non Swift…
Quando avrai tempo sarebbe bello fare anche Typescript che è sempre più
utilizzato..
Grazie mille di tutto

ciao

Il giorno mer 6 apr 2022 alle 10:22 Alexandru Mariuti <
***@***.***> ha scritto:

**Comment by nank1ro** [comment]
Scusami non avevo ben capito il problema, risolvo subito in una PR.
@all-contributors please add @crishrpz for bug

Sì Typescript verrà sicuramente aggiunto.
