### ISSUE TITLE
[Bug] l'esercizio "it/python/arithmeticOperators/20.md" ha un problema

### ISSUE THREAD

**Issue by Mattia2709** [nank1ro/codigo-questions#88]
Continua a darmi errore anche se la risposta è corretta

**Comment by nank1ro** [comment]
Ciao,

lato mio funziona correttamente, ecco la soluzione così puoi confrontarla col tuo codice:
```py
entrate = 2000
costi = 750
guadagno = entrate - costi
print(guadagno)
```
