### ISSUE TITLE
[Bug] exercise "en/python/booleans/9.md" has an issue

### ISSUE THREAD

**Issue by hohenheim98** [nank1ro/codigo-questions#93]
![E5608C94-BE94-426E-B6BB-24352D7E8424](https://user-images.githubusercontent.com/84279825/168106633-1a41cc88-dc4c-4d51-bec7-debe16bbce12.png)

**Comment by nank1ro** [comment]
Hi,

the solution is: 
```python
power=True
```

`"True"` is not a Boolean, but a String.
